import { AIGCClip, FontFamily, FontSize, FontStyleItem } from "./define";

/** 示例视频url */
export const video1Url = "./加油站.mp4";

export const fontFamilyList: FontFamily[] = [
  "宋体-简",
  "行楷-简",
  "雅痞-简",
  "报隶-简",
  "凌慧体-简",
];

export const fontStyleList: FontStyleItem[] = [
  {
    id: 8,
    name: "花字8",
    fontStyle: {
      /** 描边 */
      stroke: [
        {
          strokeStyle: "#36ff00",
          lineWidth: 4,
          lineJoin: "round",
        },
      ],
      /** 填充 */
      fill: {
        color: "#004ee6",
      },
    },
  },
  {
    id: 1,
    name: "花字1",
    fontStyle: {
      shadow: {
        shadowColor: "rgba(0, 0, 0, 0.50)",
        shadowBlur: 6,
        shadowOffsetX: 2,
        shadowOffsetY: 2,
      },
      /** 填充 */
      fill: {
        color: "white",
      },
    },
  },
  {
    id: 14,
    name: "花字14",
    fontStyle: {
      /** 描边 */
      stroke: [
        {
          strokeStyle: "#ab2002",
          lineWidth: 4,
          strokeOffsetY: 1,
          strokeOffsetX: 1,
          lineJoin: "round",
        },
        {
          strokeStyle: "#ab2002",
          lineWidth: 4,
          lineJoin: "round",
        },
        {
          strokeStyle: "#efefd1",
          lineWidth: 3,
          lineJoin: "round",
        },
      ],
      /** 填充 */
      fill: {
        color: "#001657",
      },
    },
  },
  {
    id: 17,
    name: "花字17",
    fontStyle: {
      /** 描边 */
      stroke: [
        {
          strokeStyle: "#D77C31",
          lineWidth: 5,
          strokeOffsetY: 0.6,
          strokeOffsetX: 0.6,
          lineJoin: "round",
        },
        {
          strokeStyle: "#FFFFFF",
          lineWidth: 4,
          lineJoin: "round",
        },
        {
          strokeStyle: "#D77C31",
          lineWidth: 2,
          lineJoin: "round",
        },
      ],
      /** 填充 */
      fill: {
        color: "#FDF9B1",
      },
    },
  },
  {
    id: 23,
    name: "花字23",
    fontStyle: {
      /** 描边 */
      stroke: [
        {
          strokeStyle: "#3ee756",
          lineWidth: 1,
          strokeOffsetX: 1,
          strokeOffsetY: 1,
          lineJoin: "round",
        },
      ],
      shadow: {
        shadowColor: "#3ee756",
        shadowBlur: 0,
        shadowOffsetX: 1,
        shadowOffsetY: 1,
      },
      /** 填充 */
      fill: {
        color: "#000000",
      },
    },
  },
];

export const lightFontStyleList: FontStyleItem[] = fontStyleList;

export const fontSizeList: FontSize[] = [12, 14, 16, 18, 24, 28, 36, 48];

export const currentConfig = {
  fontFamily: fontFamilyList[0],
  fontStyleId: 1,
  lightFontStyleId: 1,
};

export const videoClipPiece: AIGCClip = {
  id: "piece",
  duration: 90,
  pointNum: 50,
  groupNum: 9,
  description: "",
  resolution: {
    width: 1862,
    height: 1080,
  },
  info: [
    {
      id: "video_1",
      point: "测试",
      group: "测试哈哈哈",
      preDuration: 0,
      duration: 22,
      hdVideoUrl: "",
      sdVideoUrl: "/static/video1",
      sens: [
        {
          id: "video_1_sen1",
          select: 0,
          text: "段一这是第一条字幕",
          textList: [],
          duration: 1.7,
          timestamp: [0, 1.7],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen2",
          select: 0,
          text: "片段一这是第二条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [1.7, 3.8],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen3",
          select: 0,
          text: "片段一这是第三条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [3.8, 5.9],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen4",
          select: 1,
          text: "片段一这是第四条字幕",
          textList: [],
          duration: 1.1,
          timestamp: [5.9, 7.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen5",
          select: 0,
          text: "片段一这是第五条字幕",
          textList: [],
          duration: 3.0,
          timestamp: [7.0, 10.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen6",
          select: 1,
          text: "片段一这是第六条字幕",
          textList: [],
          duration: 1.5,
          timestamp: [10.0, 11.5],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen7",
          select: 0,
          text: "片段一这是第七条字幕",
          textList: [],
          duration: 2.5,
          timestamp: [11.5, 14.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen8",
          select: 1,
          text: "片段一这是第八条字幕",
          textList: [],
          duration: 4.0,
          timestamp: [14.0, 18.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen9",
          select: 0,
          text: "片段一这是第九条字幕",
          textList: [],
          duration: 2.0,
          timestamp: [18.0, 20.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen10",
          select: 0,
          text: "片段一这是第十条字幕",
          textList: [],
          duration: 3.0,
          timestamp: [20.0, 23.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
      ],
    },
    {
      id: "video_2",
      point: "测试",
      group: "测试哈哈哈",
      preDuration: 23,
      duration: 25,
      hdVideoUrl: "",
      sdVideoUrl: "/static/video2",
      sens: [
        {
          id: "video_2_sen1",
          select: 0,
          text: "片段二这是第一条字幕",
          textList: [],
          duration: 1.7,
          timestamp: [0, 1.7],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen2",
          select: 0,
          text: "片段二这是第二条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [1.7, 3.8],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen3",
          select: 0,
          text: "片段二这是第三条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [3.8, 5.9],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen4",
          select: 1,
          text: "片段二这是第四条字幕",
          textList: [],
          duration: 1.1,
          timestamp: [5.9, 7.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen5",
          select: 1,
          text: "片段二这是第五条字幕",
          textList: [],
          duration: 3.0,
          timestamp: [7.0, 10.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen6",
          select: 1,
          text: "片段二这是第六条字幕",
          textList: [],
          duration: 1.5,
          timestamp: [10.0, 11.5],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen7",
          select: 1,
          text: "片段二这是第七条字幕",
          textList: [],
          duration: 2.5,
          timestamp: [11.5, 14.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen8",
          select: 1,
          text: "片段二这是第八条字幕",
          textList: [],
          duration: 4.0,
          timestamp: [14.0, 18.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen9",
          select: 0,
          text: "片段二这是第九条字幕",
          textList: [],
          duration: 5.0,
          timestamp: [18.0, 23.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen10",
          select: 0,
          text: "片段二这是第十条字幕",
          textList: [],
          duration: 2.0,
          timestamp: [23.0, 25.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
      ],
    },
    {
      id: "video_3",
      point: "测试",
      group: "测试哈哈哈",
      preDuration: 48,
      duration: 24,
      hdVideoUrl: "",
      sdVideoUrl: "/static/video3",
      sens: [
        {
          id: "video_3_sen1",
          select: 0,
          text: "片段三这是第一条字幕",
          textList: [],
          duration: 1.7,
          timestamp: [0, 1.7],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen2",
          select: 0,
          text: "片段三这是第二条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [1.7, 3.8],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen3",
          select: 0,
          text: "片段三这是第三条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [3.8, 5.9],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen4",
          select: 1,
          text: "片段三这是第四条字幕",
          textList: [],
          duration: 1.1,
          timestamp: [5.9, 7.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen5",
          select: 1,
          text: "片段三这是第五条字幕",
          textList: [],
          duration: 3.0,
          timestamp: [7.0, 10.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen6",
          select: 1,
          text: "片段三这是第六条字幕",
          textList: [],
          duration: 1.5,
          timestamp: [10.0, 11.5],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen7",
          select: 1,
          text: "片段三这是第七条字幕",
          textList: [],
          duration: 2.5,
          timestamp: [11.5, 14.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen8",
          select: 1,
          text: "片段三这是第八条字幕",
          textList: [],
          duration: 4.0,
          timestamp: [14.0, 18.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen9",
          select: 0,
          text: "片段三这是第九条字幕",
          textList: [],
          duration: 2.0,
          timestamp: [18.0, 20.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen10",
          select: 0,
          text: "片段三这是第十条字幕",
          textList: [],
          duration: 4.0,
          timestamp: [20.0, 24.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
      ],
    },
  ],
};
