import { AIGCClip, FontFamily, FontSize, FontStyle } from "./define";

/** 示例视频url */
export const video1Url = "./加油站.mp4";

export const fontFamilyList: FontFamily[] = [
  "宋体-简",
  "行楷-简",
  "雅痞-简",
  "报隶-简",
  "凌慧体-简",
];

export const fontStyleList: FontStyle[] = [
  {
    id: 1,
    name: "花字一",
    svgText: `<svg xmlns="http://www.w3.org/2000/svg" id="图层_1" data-name="图层 1" viewBox="0 0 75.84 40.55"><defs><style>.cls-1,.cls-2,.cls-3,.cls-4,.cls-5{font-size:36px;font-family:SourceHanSansCN-Bold-GBpc-EUC-H, Source Han Sans CN;}.cls-1,.cls-5{fill:#e20026;}.cls-1{stroke:#e20026;}.cls-1,.cls-2,.cls-3{stroke-linecap:round;stroke-linejoin:round;}.cls-1,.cls-2{stroke-width:3px;}.cls-2{fill:#fff;stroke:#fff;}.cls-3{stroke:#000;stroke-width:2px;}.cls-4{fill:#a9e8ff;}</style></defs><title>16</title><text class="cls-1" transform="translate(2.34 34.35)">花字</text><text class="cls-2" transform="translate(1.74 33.85)">花字</text><text class="cls-3" transform="translate(1.74 33.85)">花字</text><text class="cls-4" transform="translate(1.74 33.85)">花字</text><text class="cls-5" transform="translate(1.74 33.85)">花字</text></svg>`,
  },
  {
    id: 2,
    name: "花字二",
    svgText: `<svg xmlns="http://www.w3.org/2000/svg" id="图层_1" data-name="图层 1" viewBox="0 0 76.74 42.05"><defs><style>.cls-1,.cls-2{font-size:36px;font-family:SourceHanSansCN-Bold-GBpc-EUC-H, Source Han Sans CN;}.cls-1{fill:#40593b;stroke:#40593b;stroke-linejoin:round;stroke-width:4px;}.cls-2{fill:#c3cf47;}</style></defs><title>7</title><text class="cls-1" transform="translate(2.74 34.85)">花字</text><text class="cls-2" transform="translate(2.74 34.85)">花字</text></svg>`,
  },
];

export const lightFontStyleList: FontStyle[] = [
  {
    id: 1,
    name: "高亮花字一",
    svgText: `<svg xmlns="http://www.w3.org/2000/svg" id="图层_1" data-name="图层 1"><defs><style>.cls-1,.cls-2{font-size:36px;font-family:SourceHanSansCN-Bold-GBpc-EUC-H, Source Han Sans CN;}.cls-1{fill:#40593b;stroke:#40593b;stroke-linejoin:round;stroke-width:4px;}.cls-2{fill:#c3cf47;}</style></defs><title>7</title><text class="cls-1" transform="translate(2.74 34.85)">花字</text><text class="cls-2" transform="translate(2.74 34.85)">花字</text></svg>`,
  },
  {
    id: 2,
    name: "高亮花字二",
    svgText: ``,
  },
];

export const fontSizeList: FontSize[] = [12, 14, 16, 18, 24, 28, 36, 48];

export const currentConfig = {
  fontFamily: fontFamilyList[0],
  fontStyleId: 1,
  lightFontStyleId: 1,
};

export const videoClipPiece: AIGCClip = {
  id: "piece",
  duration: 90,
  pointNum: 50,
  groupNum: 9,
  description: "",
  resolution: {
    width: 1862,
    height: 1080,
  },
  info: [
    {
      id: "video_1",
      point: "测试",
      group: "测试哈哈哈",
      preDuration: 0,
      duration: 22,
      hdVideoUrl: "",
      sdVideoUrl: "/static/video1",
      sens: [
        {
          id: "video_1_sen1",
          select: 0,
          text: "片段一这是第一条字幕",
          textList: [],
          duration: 1.7,
          timestamp: [0, 1.7],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen2",
          select: 0,
          text: "片段一这是第二条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [1.7, 3.8],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen3",
          select: 0,
          text: "片段一这是第三条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [3.8, 5.9],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen4",
          select: 1,
          text: "片段一这是第四条字幕",
          textList: [],
          duration: 1.1,
          timestamp: [5.9, 7.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen5",
          select: 0,
          text: "片段一这是第五条字幕",
          textList: [],
          duration: 3.0,
          timestamp: [7.0, 10.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen6",
          select: 1,
          text: "片段一这是第六条字幕",
          textList: [],
          duration: 1.5,
          timestamp: [10.0, 11.5],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen7",
          select: 0,
          text: "片段一这是第七条字幕",
          textList: [],
          duration: 2.5,
          timestamp: [11.5, 14.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen8",
          select: 1,
          text: "片段一这是第八条字幕",
          textList: [],
          duration: 4.0,
          timestamp: [14.0, 18.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen9",
          select: 0,
          text: "片段一这是第九条字幕",
          textList: [],
          duration: 2.0,
          timestamp: [18.0, 20.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_1_sen10",
          select: 0,
          text: "片段一这是第十条字幕",
          textList: [],
          duration: 3.0,
          timestamp: [20.0, 23.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
      ],
    },
    {
      id: "video_2",
      point: "测试",
      group: "测试哈哈哈",
      preDuration: 23,
      duration: 25,
      hdVideoUrl: "",
      sdVideoUrl: "/static/video2",
      sens: [
        {
          id: "video_2_sen1",
          select: 0,
          text: "片段二这是第一条字幕",
          textList: [],
          duration: 1.7,
          timestamp: [0, 1.7],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen2",
          select: 0,
          text: "片段二这是第二条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [1.7, 3.8],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen3",
          select: 0,
          text: "片段二这是第三条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [3.8, 5.9],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen4",
          select: 1,
          text: "片段二这是第四条字幕",
          textList: [],
          duration: 1.1,
          timestamp: [5.9, 7.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen5",
          select: 1,
          text: "片段二这是第五条字幕",
          textList: [],
          duration: 3.0,
          timestamp: [7.0, 10.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen6",
          select: 1,
          text: "片段二这是第六条字幕",
          textList: [],
          duration: 1.5,
          timestamp: [10.0, 11.5],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen7",
          select: 1,
          text: "片段二这是第七条字幕",
          textList: [],
          duration: 2.5,
          timestamp: [11.5, 14.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen8",
          select: 1,
          text: "片段二这是第八条字幕",
          textList: [],
          duration: 4.0,
          timestamp: [14.0, 18.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen9",
          select: 0,
          text: "片段二这是第九条字幕",
          textList: [],
          duration: 5.0,
          timestamp: [18.0, 23.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_2_sen10",
          select: 0,
          text: "片段二这是第十条字幕",
          textList: [],
          duration: 2.0,
          timestamp: [23.0, 25.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
      ],
    },
    {
      id: "video_3",
      point: "测试",
      group: "测试哈哈哈",
      preDuration: 48,
      duration: 24,
      hdVideoUrl: "",
      sdVideoUrl: "/static/video3",
      sens: [
        {
          id: "video_3_sen1",
          select: 0,
          text: "片段三这是第一条字幕",
          textList: [],
          duration: 1.7,
          timestamp: [0, 1.7],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen2",
          select: 0,
          text: "片段三这是第二条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [1.7, 3.8],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen3",
          select: 0,
          text: "片段三这是第三条字幕",
          textList: [],
          duration: 2.1,
          timestamp: [3.8, 5.9],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen4",
          select: 1,
          text: "片段三这是第四条字幕",
          textList: [],
          duration: 1.1,
          timestamp: [5.9, 7.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen5",
          select: 1,
          text: "片段三这是第五条字幕",
          textList: [],
          duration: 3.0,
          timestamp: [7.0, 10.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen6",
          select: 1,
          text: "片段三这是第六条字幕",
          textList: [],
          duration: 1.5,
          timestamp: [10.0, 11.5],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen7",
          select: 1,
          text: "片段三这是第七条字幕",
          textList: [],
          duration: 2.5,
          timestamp: [11.5, 14.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen8",
          select: 1,
          text: "片段三这是第八条字幕",
          textList: [],
          duration: 4.0,
          timestamp: [14.0, 18.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen9",
          select: 0,
          text: "片段三这是第九条字幕",
          textList: [],
          duration: 2.0,
          timestamp: [18.0, 20.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
        {
          id: "video_3_sen10",
          select: 0,
          text: "片段三这是第十条字幕",
          textList: [],
          duration: 4.0,
          timestamp: [20.0, 24.0],
          originTimestamp: [],
          svgText: "",
          imgUrl: "",
        },
      ],
    },
  ],
};
